Repository hashgraph/hedera-protobufs-cpp, pull requests merged in 2023-01, with the labels that each got.

#9 Add missing build dependecies
  .github/workflows/zxc-build-library.yaml
Labels: Feature Enhancement

#8 Build OpenSSL from source
  BuildOpenSSL.cmake
  CMakeLists.txt
  src/proto/CMakeLists.txt
  vcpkg.json
Labels: New Feature

#15 Upgrade to v0.33 of Hedera protobufs
  CMakeLists.txt
  src/proto/CMakeLists.txt
Labels: Improvement
